//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/Test.proto
namespace Protocol.TEST.test
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_TEST_Test1")]
  public partial class MSG_TEST_Test1 : global::ProtoBuf.IExtensible
  {
    public MSG_TEST_Test1() {}
    
    private int _testint;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"testint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int testint
    {
      get { return _testint; }
      set { _testint = value; }
    }
    private string _teststring;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teststring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string teststring
    {
      get { return _teststring; }
      set { _teststring = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_TEST_Test2")]
  public partial class MSG_TEST_Test2 : global::ProtoBuf.IExtensible
  {
    public MSG_TEST_Test2() {}
    
    private int _testint;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"testint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int testint
    {
      get { return _testint; }
      set { _testint = value; }
    }
    private string _teststring;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teststring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string teststring
    {
      get { return _teststring; }
      set { _teststring = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_TEST_Test3")]
  public partial class MSG_TEST_Test3 : global::ProtoBuf.IExtensible
  {
    public MSG_TEST_Test3() {}
    
    private int _testint;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"testint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int testint
    {
      get { return _testint; }
      set { _testint = value; }
    }
    private string _teststring;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teststring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string teststring
    {
      get { return _teststring; }
      set { _teststring = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}