 //------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated by a tool.(The author is Boiling)
 //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------
namespace Protocol.A.A2B
{
     public class Generater
     {
          public static void GenerateId()
          {
               Protocol.MsgId.Id<A2BTest1>.Value= 0xff00001;
               Protocol.MsgId.Id<A2BTest2>.Value= 0xff00002;
               Protocol.MsgId.Id<A2BTest3>.Value= 0xff00003;
          }
     }
}
