// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleManager/Protocol/BM2B.CODE.proto

#ifndef PROTOBUF_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto__INCLUDED
#define PROTOBUF_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsMSG_BM2B_HEARTBEATImpl();
void InitDefaultsMSG_BM2B_HEARTBEAT();
void InitDefaultsMSG_BM2B_RETRUN_REGISTERImpl();
void InitDefaultsMSG_BM2B_RETRUN_REGISTER();
inline void InitDefaults() {
  InitDefaultsMSG_BM2B_HEARTBEAT();
  InitDefaultsMSG_BM2B_RETRUN_REGISTER();
}
}  // namespace protobuf_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto
namespace Protocol {
namespace BattleManager {
namespace BM2B {
class MSG_BM2B_HEARTBEAT;
class MSG_BM2B_HEARTBEATDefaultTypeInternal;
extern MSG_BM2B_HEARTBEATDefaultTypeInternal _MSG_BM2B_HEARTBEAT_default_instance_;
class MSG_BM2B_RETRUN_REGISTER;
class MSG_BM2B_RETRUN_REGISTERDefaultTypeInternal;
extern MSG_BM2B_RETRUN_REGISTERDefaultTypeInternal _MSG_BM2B_RETRUN_REGISTER_default_instance_;
}  // namespace BM2B
}  // namespace BattleManager
}  // namespace Protocol
namespace Protocol {
namespace BattleManager {
namespace BM2B {

// ===================================================================

class MSG_BM2B_HEARTBEAT : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Protocol.BattleManager.BM2B.MSG_BM2B_HEARTBEAT) */ {
 public:
  MSG_BM2B_HEARTBEAT();
  virtual ~MSG_BM2B_HEARTBEAT();

  MSG_BM2B_HEARTBEAT(const MSG_BM2B_HEARTBEAT& from);

  inline MSG_BM2B_HEARTBEAT& operator=(const MSG_BM2B_HEARTBEAT& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MSG_BM2B_HEARTBEAT(MSG_BM2B_HEARTBEAT&& from) noexcept
    : MSG_BM2B_HEARTBEAT() {
    *this = ::std::move(from);
  }

  inline MSG_BM2B_HEARTBEAT& operator=(MSG_BM2B_HEARTBEAT&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_BM2B_HEARTBEAT& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MSG_BM2B_HEARTBEAT* internal_default_instance() {
    return reinterpret_cast<const MSG_BM2B_HEARTBEAT*>(
               &_MSG_BM2B_HEARTBEAT_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MSG_BM2B_HEARTBEAT* other);
  friend void swap(MSG_BM2B_HEARTBEAT& a, MSG_BM2B_HEARTBEAT& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MSG_BM2B_HEARTBEAT* New() const PROTOBUF_FINAL { return New(NULL); }

  MSG_BM2B_HEARTBEAT* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MSG_BM2B_HEARTBEAT& from);
  void MergeFrom(const MSG_BM2B_HEARTBEAT& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MSG_BM2B_HEARTBEAT* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 GroupId = 1;
  bool has_groupid() const;
  void clear_groupid();
  static const int kGroupIdFieldNumber = 1;
  ::google::protobuf::int32 groupid() const;
  void set_groupid(::google::protobuf::int32 value);

  // required int32 SubId = 2;
  bool has_subid() const;
  void clear_subid();
  static const int kSubIdFieldNumber = 2;
  ::google::protobuf::int32 subid() const;
  void set_subid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.BattleManager.BM2B.MSG_BM2B_HEARTBEAT)
 private:
  void set_has_groupid();
  void clear_has_groupid();
  void set_has_subid();
  void clear_has_subid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 groupid_;
  ::google::protobuf::int32 subid_;
  friend struct ::protobuf_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto::TableStruct;
  friend void ::protobuf_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto::InitDefaultsMSG_BM2B_HEARTBEATImpl();
};
// -------------------------------------------------------------------

class MSG_BM2B_RETRUN_REGISTER : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Protocol.BattleManager.BM2B.MSG_BM2B_RETRUN_REGISTER) */ {
 public:
  MSG_BM2B_RETRUN_REGISTER();
  virtual ~MSG_BM2B_RETRUN_REGISTER();

  MSG_BM2B_RETRUN_REGISTER(const MSG_BM2B_RETRUN_REGISTER& from);

  inline MSG_BM2B_RETRUN_REGISTER& operator=(const MSG_BM2B_RETRUN_REGISTER& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MSG_BM2B_RETRUN_REGISTER(MSG_BM2B_RETRUN_REGISTER&& from) noexcept
    : MSG_BM2B_RETRUN_REGISTER() {
    *this = ::std::move(from);
  }

  inline MSG_BM2B_RETRUN_REGISTER& operator=(MSG_BM2B_RETRUN_REGISTER&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_BM2B_RETRUN_REGISTER& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MSG_BM2B_RETRUN_REGISTER* internal_default_instance() {
    return reinterpret_cast<const MSG_BM2B_RETRUN_REGISTER*>(
               &_MSG_BM2B_RETRUN_REGISTER_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MSG_BM2B_RETRUN_REGISTER* other);
  friend void swap(MSG_BM2B_RETRUN_REGISTER& a, MSG_BM2B_RETRUN_REGISTER& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MSG_BM2B_RETRUN_REGISTER* New() const PROTOBUF_FINAL { return New(NULL); }

  MSG_BM2B_RETRUN_REGISTER* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MSG_BM2B_RETRUN_REGISTER& from);
  void MergeFrom(const MSG_BM2B_RETRUN_REGISTER& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MSG_BM2B_RETRUN_REGISTER* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 GroupId = 1;
  bool has_groupid() const;
  void clear_groupid();
  static const int kGroupIdFieldNumber = 1;
  ::google::protobuf::int32 groupid() const;
  void set_groupid(::google::protobuf::int32 value);

  // required int32 SubId = 2;
  bool has_subid() const;
  void clear_subid();
  static const int kSubIdFieldNumber = 2;
  ::google::protobuf::int32 subid() const;
  void set_subid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.BattleManager.BM2B.MSG_BM2B_RETRUN_REGISTER)
 private:
  void set_has_groupid();
  void clear_has_groupid();
  void set_has_subid();
  void clear_has_subid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 groupid_;
  ::google::protobuf::int32 subid_;
  friend struct ::protobuf_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto::TableStruct;
  friend void ::protobuf_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto::InitDefaultsMSG_BM2B_RETRUN_REGISTERImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MSG_BM2B_HEARTBEAT

// required int32 GroupId = 1;
inline bool MSG_BM2B_HEARTBEAT::has_groupid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_BM2B_HEARTBEAT::set_has_groupid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_BM2B_HEARTBEAT::clear_has_groupid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_BM2B_HEARTBEAT::clear_groupid() {
  groupid_ = 0;
  clear_has_groupid();
}
inline ::google::protobuf::int32 MSG_BM2B_HEARTBEAT::groupid() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleManager.BM2B.MSG_BM2B_HEARTBEAT.GroupId)
  return groupid_;
}
inline void MSG_BM2B_HEARTBEAT::set_groupid(::google::protobuf::int32 value) {
  set_has_groupid();
  groupid_ = value;
  // @@protoc_insertion_point(field_set:Protocol.BattleManager.BM2B.MSG_BM2B_HEARTBEAT.GroupId)
}

// required int32 SubId = 2;
inline bool MSG_BM2B_HEARTBEAT::has_subid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_BM2B_HEARTBEAT::set_has_subid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_BM2B_HEARTBEAT::clear_has_subid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_BM2B_HEARTBEAT::clear_subid() {
  subid_ = 0;
  clear_has_subid();
}
inline ::google::protobuf::int32 MSG_BM2B_HEARTBEAT::subid() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleManager.BM2B.MSG_BM2B_HEARTBEAT.SubId)
  return subid_;
}
inline void MSG_BM2B_HEARTBEAT::set_subid(::google::protobuf::int32 value) {
  set_has_subid();
  subid_ = value;
  // @@protoc_insertion_point(field_set:Protocol.BattleManager.BM2B.MSG_BM2B_HEARTBEAT.SubId)
}

// -------------------------------------------------------------------

// MSG_BM2B_RETRUN_REGISTER

// required int32 GroupId = 1;
inline bool MSG_BM2B_RETRUN_REGISTER::has_groupid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_BM2B_RETRUN_REGISTER::set_has_groupid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_BM2B_RETRUN_REGISTER::clear_has_groupid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_BM2B_RETRUN_REGISTER::clear_groupid() {
  groupid_ = 0;
  clear_has_groupid();
}
inline ::google::protobuf::int32 MSG_BM2B_RETRUN_REGISTER::groupid() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleManager.BM2B.MSG_BM2B_RETRUN_REGISTER.GroupId)
  return groupid_;
}
inline void MSG_BM2B_RETRUN_REGISTER::set_groupid(::google::protobuf::int32 value) {
  set_has_groupid();
  groupid_ = value;
  // @@protoc_insertion_point(field_set:Protocol.BattleManager.BM2B.MSG_BM2B_RETRUN_REGISTER.GroupId)
}

// required int32 SubId = 2;
inline bool MSG_BM2B_RETRUN_REGISTER::has_subid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_BM2B_RETRUN_REGISTER::set_has_subid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_BM2B_RETRUN_REGISTER::clear_has_subid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_BM2B_RETRUN_REGISTER::clear_subid() {
  subid_ = 0;
  clear_has_subid();
}
inline ::google::protobuf::int32 MSG_BM2B_RETRUN_REGISTER::subid() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleManager.BM2B.MSG_BM2B_RETRUN_REGISTER.SubId)
  return subid_;
}
inline void MSG_BM2B_RETRUN_REGISTER::set_subid(::google::protobuf::int32 value) {
  set_has_subid();
  subid_ = value;
  // @@protoc_insertion_point(field_set:Protocol.BattleManager.BM2B.MSG_BM2B_RETRUN_REGISTER.SubId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace BM2B
}  // namespace BattleManager
}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleManager_2fProtocol_2fBM2B_2eCODE_2eproto__INCLUDED
